export const OBJECT_HEIGHT = 80
export const GROUP_PADDING_TOP = 50
export const ITEM_GAP = 10
export const THROTTLE_MS = 10
export const SAVING_THROTTLE = 300
export const FLOW_KEY = 'datamapper-flow-key'
export const TABLE_WIDTH = 500
export const MAPPING_TABLE_WIDTH = TABLE_WIDTH / 3
export const MAPPING_WIDTH = MAPPING_TABLE_WIDTH - 20
export const PROPERTY_WIDTH = TABLE_WIDTH - 300
export const GROUP_WIDTH = TABLE_WIDTH - 30
export const SCROLL_AMOUNT = 10
export const SCROLL_PANE_HEIGHT = 150
