services:
  flow:
    image: ghcr.io/frankframework/flow:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: cloud
    ports:
      - "8080:8080"
