services:
  flow:
    image: ghcr.io/frankframework/flow:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      management.gateway.outbound.class: org.frankframework.management.gateway.HazelcastOutboundGateway
      logger.com.hazelcast: debug
    ports:
      - "8080:8080"
      - "5700-5709:5700-5709"

  ff-test:
    image: frankframework/frankframework:latest
    ports:
      - "8081:8080"
      - "5710-5720:5700-5710"
    environment:
      jdbc.required: false
      larva.adapter.active: false
      management.gateway.inbound.class: org.frankframework.management.gateway.HazelcastInboundGateway
      management.gateway.outbound.class: org.frankframework.management.gateway.HazelcastOutboundGateway
