spring.application.name=Flow
cors.allowed.origins=*

spring.web.resources.static-locations=classpath:/frontend/

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.servlet.session.timeout=86400s
server.servlet.session.cookie.max-age=86400
