export const FlowConfig = {
  NODE_DEFAULT_WIDTH: 300,
  NODE_DEFAULT_HEIGHT: 200,
  EXIT_DEFAULT_WIDTH: 150,
  EXIT_DEFAULT_HEIGHT: 100,
  STICKY_NOTE_DEFAULT_WIDTH: 200,
  STICKY_NOTE_DEFAULT_HEIGHT: 200,
  COPY_PASTE_OFFSET: 40,
}
