export const FlowConfig = {
  NODE_DEFAULT_WIDTH: 300,
  NODE_MIN_HEIGHT: 80,
  NODE_ZOOMED_OUT_HEIGHT: 380,
  EXIT_DEFAULT_WIDTH: 150,
  EXIT_DEFAULT_HEIGHT: 100,
  STICKY_NOTE_DEFAULT_WIDTH: 200,
  STICKY_NOTE_DEFAULT_HEIGHT: 200,
  STICKY_NOTE_MAX_HEIGHT: 500,
  STICKY_NOTE_BALLOON_WIDTH: 160,
  STICKY_NOTE_BALLOON_HEIGHT: 58,
  COPY_PASTE_OFFSET: 40,
  MAX_HISTORY: 20, // Adjust this value as needed to limit the number of undo steps
  LAYOUT_HORIZONTAL_OFFSET: 300,
  LAYOUT_VERTICAL_OFFSET: 200,
}
